---
- hosts: master1-instance
  become: true
  tasks:
    - name: Print manager token
      shell: docker swarm join-token manager | grep 'docker swarm join' | sed 's/^\t//'
      register: manager_token
    - name: Log token
      debug: 
        msg: "{{ manager_token.stdout_lines }}"

- hosts: othermasters
  become: true
  vars:
    manager_token: "{{ hostvars['master1-instance']['manager_token']['stdout'] }}"
  tasks:
    - name: Join Manager Nodes
      command: "{{ manager_token }}"
      register: output

    - name: Log token
      debug: 
        msg: "{{ output.stdout_lines }}"
