- hosts: firstmaster
  become: true
  tasks:
  - name: Init cluster
    shell: "docker swarm init --advertise-addr={{ hostvars['node1'].ansible_host }}"
    register: docker_init
  - name: Print docker init
    debug:
      msg: "{{ docker_init.stdout_lines }}"
