- hosts: master1-instance
  become: true
  tasks:
  - name: Get docker compose file
    shell: curl -L https://downloads.portainer.io/ce2-19/portainer-agent-stack.yml -o portainer-agent-stack.yml
  - name: Deploy stack
    shell: docker stack deploy -c portainer-agent-stack.yml portainer
