---
- hosts: node1
  become: true
  tasks:
    - name: Print worker token
      shell: docker swarm join-token worker | grep 'docker swarm join' | sed 's/^\t//'
      register: worker_token
    - name: Log token
      debug: 
        msg: "{{ worker_token.stdout_lines }}"

- hosts: workers
  become: true
  vars:
    worker_token: "{{ hostvars['node1']['worker_token']['stdout'] }}"
  tasks:
    - name: Join Worker Nodes
      command: "{{ worker_token }}"
      register: output

    - name: Log token
      debug: 
        msg: "{{ output.stdout_lines }}"
