version: "3.9"  # Adjust as needed

services:
  nginx:
    image: nginx:1.14.2
    ports:
      - "80:80"  # Map container port 80 to host port 80
    volumes:
      - ./your-app:/usr/share/nginx/html:ro  # Mount your web app directory
